export const demoBadgesCatalog = {
  first_landing: {
    id: 'first_landing',
    name: 'First Landing',
    desc: 'Took your first step — completed your first quest at ASU',
    color: 'gold',
  },
  culture_bridge: {
    id: 'culture_bridge',
    name: 'Culture Bridge',
    desc: 'Connected with someone from a different country',
    color: 'teal',
  },
  globe_trotter: {
    id: 'globe_trotter',
    name: 'Globe Trotter',
    desc: 'Visited 4 different zones across campus',
    color: 'gold',
  },
  zone_dj: {
    id: 'zone_dj',
    name: 'Zone DJ',
    desc: 'Added 5 songs to zone queues — your music, your identity',
    color: 'teal',
  },
  kindred_spirit: {
    id: 'kindred_spirit',
    name: 'Kindred Spirit',
    desc: 'Waved back at someone — found a moment of real connection',
    color: 'teal',
  },
  hometown_hero: {
    id: 'hometown_hero',
    name: 'Hometown Hero',
    desc: 'Completed a legend quest — went above and beyond',
    color: 'maroon',
  },
  sun_devil_streak: {
    id: 'sun_devil_streak',
    name: 'Sun Devil Streak',
    desc: 'Showed up 7 days in a row — you belong here',
    color: 'gold',
  },
}

export const demoInitialUser = {
  id: 'nysa',
  name: 'Nysa J.',
  initials: 'NJ',
  level: 4,
  title: 'Globe Trotter',
  xp: 340,
  xp_next: 500,
  country: 'India',
  flag: '🇮🇳',
  languages: ['Hindi', 'English'],
  quests_done: 12,
  connections_made: 5,
  cultures_met: 4,
  songs_queued: 3,
  badges: ['first_landing', 'zone_dj', 'globe_trotter'],
  completed_quests: [],
}

export const demoClassRoster = {
  my_classes: ['CSE 310', 'MAT 243', 'COM 225', 'FSE 150'],
  classmates: [
    { name: 'Priya M.',  initials: 'PM', classes: ['CSE 310', 'COM 225'] },
    { name: 'Chen W.',   initials: 'CW', classes: ['MAT 243'] },
    { name: 'Tariq O.',  initials: 'TO', classes: ['FSE 150', 'COM 225'] },
    { name: 'Lucas R.',  initials: 'LR', classes: ['CSE 310'] },
    { name: 'Ji-ho K.',  initials: 'JK', classes: ['MAT 243', 'CSE 310'] },
    { name: 'Amir N.',   initials: 'AN', classes: ['COM 225', 'FSE 150'] },
    { name: 'Sofia E.',  initials: 'SE', classes: ['CSE 310'] },
    { name: 'Kenji T.',  initials: 'KT', classes: ['MAT 243'] },
  ]
}

export const demoZones = [
  {
    id: 'mu',
    name: 'Memorial Union',
    sublocation: '3rd floor',
    distance: 'you are here',
    students_here: 8,
    countries_here: 6,
    country_flags: ['🇮🇳', '🇨🇳', '🇲🇽', '🇧🇷', '🇰🇷', '🇳🇬'],
    classmates_here: 2,
    color: 'gold',
    is_current: true,
    now_playing: 'Doechii — Denial Is A River',
    queue: ['Charli xcx — 360', 'Frank Ocean — Nights', 'SZA — Snooze'],
    listeners: 9,
    quest: {
      id: 'mu_buddy',
      type: 'icebreaker',
      title: 'Find a study buddy',
      desc: "Sit near someone you don't know and work in the same space for 30 mins. Ask where they're from. Both tap done to confirm.",
      xp: 60,
      status: 'available',
    },
  },
  {
    id: 'library',
    name: 'Hayden Library',
    sublocation: 'Lower Level',
    distance: '0.3 mi',
    students_here: 14,
    countries_here: 9,
    country_flags: ['🇵🇰', '🇯🇵', '🇫🇷', '🇩🇪', '🇿🇦', '🇨🇴', '🇪🇬', '🇹🇷', '🇦🇺'],
    classmates_here: 1,
    color: 'maroon',
    is_current: false,
    now_playing: 'Tyler, the Creator — See You Again',
    queue: ['SZA — Kill Bill', 'Mitski — Nobody', 'Bon Iver — Holocene'],
    listeners: 14,
    quest: {
      id: 'lib_study',
      type: 'explorer',
      title: 'Silent study ritual',
      desc: "Study for 45 minutes without your phone — just like you'd focus back home. Check in when you arrive, check out when done.",
      xp: 80,
      status: 'available',
    },
  },
  {
    id: 'palm_walk',
    name: 'Palm Walk',
    sublocation: 'outdoor seating',
    distance: '0.5 mi',
    students_here: 22,
    countries_here: 12,
    country_flags: ['🇻🇳', '🇧🇩', '🇵🇭', '🇨🇱', '🇰🇪', '🇮🇷', '🇵🇪', '🇬🇭', '🇮🇩', '🇺🇦', '🇪🇹', '🇷🇴'],
    classmates_here: 1,
    color: 'gold',
    is_current: false,
    now_playing: 'Kendrick Lamar — Not Like Us',
    queue: ['Ice Spice — Gimmie A Light', 'Benson Boone — Beautiful Things'],
    listeners: 22,
    quest: {
      id: 'palm_boss',
      type: 'legend',
      title: 'Share your table',
      desc: 'Sit at a table where someone else is eating alone. Say hey. Ask what they miss most about home.',
      xp: 150,
      status: 'available',
    },
  },
  {
    id: 'coor_hall',
    name: 'Coor Hall',
    sublocation: 'lobby',
    distance: '0.7 mi',
    students_here: 6,
    countries_here: 4,
    country_flags: ['🇲🇾', '🇸🇦', '🇪🇸', '🇳🇵'],
    classmates_here: 1,
    color: 'maroon',
    is_current: false,
    now_playing: 'Lorde — Royals',
    queue: ['Billie Eilish — Birds of a Feather', 'Gracie Abrams — Risk'],
    listeners: 6,
    quest: {
      id: 'coor_convo',
      type: 'explorer',
      title: 'Teach someone a word',
      desc: 'Say hello to someone in your language and teach them how to say it.',
      xp: 40,
      status: 'available',
    },
  },
]

export const demoLeaderboard = [
  { rank: 1, name: 'Priya M.', initials: 'PM', title: 'World Citizen', xp: 820, color: 'teal', flag: '🇮🇳', country: 'India', is_me: false },
  { rank: 2, name: 'Chen W.', initials: 'CW', title: 'Culture Bridge', xp: 710, color: 'gold', flag: '🇨🇳', country: 'China', is_me: false },
  { rank: 3, name: 'Asmi K.', initials: 'AK', title: 'Globe Trotter', xp: 490, color: 'maroon', flag: '🇮🇳', country: 'India', is_me: false },
  { rank: 4, name: 'Nysa J.', initials: 'NJ', title: 'Globe Trotter', xp: 340, color: 'gold', flag: '🇮🇳', country: 'India', is_me: true },
  { rank: 5, name: 'Tariq O.', initials: 'TO', title: 'Scout', xp: 210, color: 'teal', flag: '🇳🇬', country: 'Nigeria', is_me: false },
  { rank: 6, name: 'Layla P.', initials: 'LP', title: 'Newcomer', xp: 175, color: 'maroon', flag: '🇸🇦', country: 'Saudi Arabia', is_me: false },
  { rank: 7, name: 'Ji-ho K.', initials: 'JK', title: 'Scout', xp: 160, color: 'teal', flag: '🇰🇷', country: 'South Korea', is_me: false },
  { rank: 8, name: 'Lucas R.', initials: 'LR', title: 'Newcomer', xp: 95, color: 'gold', flag: '🇧🇷', country: 'Brazil', is_me: false },
]

export const demoRecentActivity = [
  { name: 'Priya', flag: '🇮🇳', action: 'connected with someone', where: 'Memorial Union', mins_ago: 2 },
  { name: 'Chen', flag: '🇨🇳', action: 'added a song to the queue', where: 'Hayden Library', mins_ago: 5 },
  { name: 'Tariq', flag: '🇳🇬', action: 'completed an icebreaker', where: 'Palm Walk', mins_ago: 8 },
  { name: 'Ji-ho', flag: '🇰🇷', action: 'earned Kindred Spirit', where: 'Coor Hall', mins_ago: 14 },
]

